input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules = 

    follow_mouse = 1
    sensitivity = -1

    touchpad {
        natural_scroll = true
        clickfinger_behavior = true
        disable_while_typing = true
        scroll_factor = 0.8
    }
}

# Touchpad gestures for workspace switching
gestures {
    workspace_swipe = true
    workspace_swipe_fingers = 3
    workspace_swipe_distance = 300
    workspace_swipe_invert = true
    workspace_swipe_min_speed_to_force = 30
}
