require("config.env")
require("config.input")
require("config.monitors")
require("config.keybinds")
require("config.windowrules")
require("config.settings")
require("config.autostart")
require("animations.classic")
