# NVIDIA environment variables
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

# NVIDIA cursor fix
cursor {
    no_hardware_cursors = true
}

input {
    kb_layout = es
    kb_variant =
    kb_model =
    kb_options = caps:escape
    kb_rules = 

    follow_mouse = 1
    sensitivity = -1
}
