hl.on("hyprland.start", function()
	hl.exec_cmd("swaync")
	hl.exec_cmd("~/.config/waybar/scripts/launch.sh")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("swayosd-server")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("systemctl --user start xdg-desktop-portal-kde")
	hl.exec_cmd("wl-paste --type text --watch cliphist store")
	hl.exec_cmd("wl-paste --type image --watch cliphist store")
	hl.exec_cmd("easyeffects --gapplication-service")
end)
